### ISSUE TITLE
Returning values from a worker

### ISSUE THREAD

**Issue by jcohen02** [lecardozo/rworker#2]
Is it possible to return values from a worker? At present, returning a value from a task function doesn't seem to result in the value being added to the message returned from the worker and I couldn't see anything about this in documentation.

The result JSON only seems to contain a progress key. It looks like the result can be captured in [worker.R L51](https://github.com/lecardozo/rworker/blob/14a1f65678d7bb4daedde5c6bdc0180f5a1cc6b9/R/worker.R#L51) and returned here but I wasn't clear if this is already being handled some other way.

Thanks, Jeremy.

**Comment by lecardozo** [comment]
You are right! In the current version, task returns are completely ignored. In my use cases (which were basically __*the*__ motivations behind the creation of this package) the tasks stored the relevant results in an external database. IMO it should not be too hard to implement this, although we could have some problems, specifically with respect to complex data serialization/deserialization.

Could you provide some detail about your use case? BTW, good to see this package may be useful for somebody else! :smiley:

**Comment by jcohen02** [comment]
I also had some concern about data serialization/deserialization and type mappings between R and Python. I don't know if there's anything that can be done using [rpy2](https://rpy2.bitbucket.io/)? I've had a go at prototyping a [simple solution](https://github.com/jcohen02/rworker/tree/feature/task_results) and this seems to work for what I _think_ I'm looking for - just being able to return a string should be OK for now (and I can serialize my data to JSON or similar). However, I guess this is not a very generic solution and something more substantial may be required?

Re use case: I'm working with a Django web app but some of the underlying (and potentially long-running) tasks that I want to run are already implemented in R. It looks like there's also stronger support in the R community in terms of libraries which makes porting everything to Python seem like it may not be the best approach. There are of course many different solutions but I like the idea of running Celery tasks to call the R code and an R-based Celery worker seems like a nice approach 😄

**Comment by lecardozo** [comment]
Your solution seems nice to me! Considering that the Celery messaging protocol is language agnostic, maybe we should stick with the JSON serialization for returned values. We just need to make sure that the returned object is JSON serializable. Would mind making a PR with your changes?

**Comment by lecardozo** [comment]
Merged here: https://github.com/lecardozo/rworker/pull/3
