### ISSUE TITLE
Example for task arguments?

### ISSUE THREAD

**Issue by josegonzalez** [lecardozo/rworker#6]
I poked through the code, and its not clear to me how task arguments work with this package. If you could provide a brief example, that would be super awesome :)

**Comment by lecardozo** [comment]
Thanks for using rworker, @josegonzalez ! Rworker was built following the Celery specs, so you should be able to send arguments to tasks in the same way you would do in Python:

```python
from celery import Celery
app = Celery(...)
kwargs = {"a": 1, "b":0}
app.send_task("your_task_defined_in_rworker", kwargs=kwargs)
```

As far as I remember (I don't touch this project for a while 😄) and given the way [Worker objects execute tasks](https://github.com/lecardozo/rworker/blob/master/R/worker.R#L52), positional arguments are currently being ignored and only kwargs are used during task execution.

**Comment by josegonzalez** [comment]
The python side makes sense, but how do I access the kwargs in the R task?

**Comment by lecardozo** [comment]
If you define your function with ellipsis, you should be able to just list it:
```r
yourTask <- function(...) {
    kwargs <- list(...)
    a <- kwargs["a"]
    b <- kwargs["b"]
    # your function definition...
}
```

Or, you could just define your function with predetermined arguments:
```r
yourTask <- function(a, b) {
    print(a)
    print(b)
    # your function definition...
}
```

Have you tried any of these approaches? This should be enough for you to access the arguments. If you are having any more trouble, please let me know! 😃
