### ISSUE TITLE
Attempting to manually execute a task crashes R

### ISSUE THREAD

**Issue by HammadTheOne** [lecardozo/rworker#7]
Hello,

When consuming tasks with `consumer$consumer` to listen to messages already in the task queue and execute them, the task is executed without issue, but when manually registering and executing a task through R, the method `rwork$execute('example_task')` aborts the current R session with a fatal error with no indication as to why. 

Here's a small sample, most of it comprised of the example in the package docs:

```r
redis_url <- 'redis://localhost:6379'

rwork <- rworker(name ='celery', workers=2, queue=redis_url, backend=redis_url)

# Register task
myfun <- function() {
    Sys.sleep(5)
}
rwork$task(myfun, name='long_running_task')

# Send task for background execution
rwork$execute('long_running_task')
```

If you could shed some light on what's going on here, I'd really appreciate it.

**Comment by lecardozo** [comment]
Hey, @HammadTheOne!

Firstly, thanks for trying `rworker`! Maybe it would be better if you explain a little bit more about your use case, so I can understand what is happening. I think you might be missing a little bit about the rworker's usage (not your fault, the documentation could be a lot better). Currently rworkers main job is to listen and execute tasks that are sent by an external process through a message broker (in this case, Redis). The `$execute` method is used internally to send the task for execution from the master rworker process to the background worker processes that really execute the tasks. If you want to execute R functions asynchronously from R itself, there are better solutions such as the [future](https://github.com/HenrikBengtsson/future) package. 😃

**Comment by HammadTheOne** [comment]
Ah I see now, thank you for the explanation. I was under the impression that the `$execute` method might also be able to send the tasks to the message broker and then subsequently execute them with the background workers. I'm wondering then, what is it that `rworker` is listening for from the message broker that might trigger the task delivery and execution?

**Comment by lecardozo** [comment]
No problem! Currently rworker polls new messages from Redis (this is the only supported message broker, for now). If you have, for example, 1 task message already available on Redis queue, rworker should automatically fetch this message and execute the task.
